# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-20 22:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180120_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 20, 22, 46, 29, 889963, tzinfo=utc)),
        ),
    ]
